name: Doxygen

on:
  push:
    branches: [ master, gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        working-directory: 'MarkdownToLatex/'
        doxyfile-path: './doxyfile'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: MarkdownToLatex/docs/html
        destination_dir: class_reference
